apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mlops-api-deployment 
  labels: 
    app: mlops-api 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mlops-api 
  template: 
    metadata:  # Hello, once again
      labels: 
        app: mlops-api  
    spec: 
      containers: 
      - name: mlops-api 
        image: gcr.io/icai2025-477208/mlops-api:latest # Usamos el project_id=icai2025-477208
        ports: 
        - name: metrics
          containerPort: 5000 