apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mlops-web-deployment 
  labels: 
    app: mlops-web 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mlops-web 
  template: 
    metadata: 
      labels: 
        app: mlops-web 
    spec: 
      containers: 
      - name: mlops-web 
        image: gcr.io/icai2025-477208/mlops-web:latest # Usamos el project_id=icai2025-477208
        ports: 
        - containerPort: 8501 
        env: 
        - name: API_URL 
          value: http://mlops-api-service:5000/predict # <--- ConexiÃ³n al servicio interno de la API 